name: Parser unit tests
on:
  push:
      branches:
        - master
        - develop
        - feature/**
        - release/**
        - hotfix/**
      # Publish `v1.2.3` tags as releases.
      tags:
        - v*
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build-windows:
    name: "Unit tests"
    runs-on: windows-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: MSBuild Version
        run: msbuild -version

      - name: Restore packages
        run: nuget restore dsmr-parser.sln

      - name: Build 
        run: msbuild.exe dsmr-parser.sln /nologo /nr:false /p:configuration="Debug"

      - name: Run tests
        working-directory: SensateIoT.SmartEnergy.Dsmr.Parser.Tests\bin\Debug
        run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:"SensateIoT.SmartEnergy.Dsmr.Parser.Tests.dll" /noisolation'
